site_name: Private Label VR Arena
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: cyan
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: cyan
      accent: light-blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/PrivateLabelVR
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@privatelabelvr8376
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/private-label-vr/

copyright: |
  &copy; 2024 <a href="https://privatelabelvr.com"  target="_blank" rel="noopener">Private Label VR</a>
